{% set name = "pygeometa" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeometa-{{ version }}.tar.gz
  sha256: ee5b14e50824664e22f80dde7fc20bf0862fd31e9bc6cc3ff8fab5cf60ed6ad2

build:
  number: 0
  noarch: python
  entry_points:
    - pygeometa=pygeometa:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - jinja2
    - jsonschema
    - pyyaml

test:
  imports:
    - pygeometa
    - pygeometa.schemas
  commands:
    - pip check
    - pygeometa --help
  requires:
    - pip

about:
  home: https://github.com/geopython/pygeometa
  license: MIT
  license_file: LICENSE.md
  summary: pygeometa is a Python package to generate metadata for geospatial datasets
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
