{% set name = "pygeometa" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeometa-{{ version }}.tar.gz
  sha256: e4dcd816120327abe06b6af35b3662c8bedaf58c55e1a0f59ceb24d0390f7f42

build:
  number: 0
  noarch: python
  entry_points:
    - pygeometa=pygeometa:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - click
    - jinja2
    - pyyaml

test:
  imports:
    - pygeometa
    - pygeometa.schemas
  commands:
    - pip check
    - pygeometa --help
  requires:
    - pip

about:
  home: https://github.com/geopython/pygeometa
  license: MIT
  license_file: LICENSE.md
  summary: pygeometa is a Python package to generate metadata for geospatial datasets
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
