{% set version = "0.6.0" %}

package:
  name: pygeometa
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pygeometa/pygeometa-{{ version }}.tar.gz
  sha256: 85493ba385af9394744f07e5e647c59624d33a76af2aedab1cdff04420ee09db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pygeometa=pygeometa:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - jinja2
    - six
    - pyyaml

test:
  imports:
    - pygeometa
  commands:
    - pygeometa --help

about:
  home: https://github.com/geopython/pygeometa
  license: MIT
  license_file: LICENSE.md
  summary: pygeometa is a Python package to generate metadata for geospatial datasets
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
