travis:
  secure:
    BINSTAR_TOKEN: QnRUPsnc2tKNfQhDjjTH9tmZZc3qTJ1vkxTFYaUr/ZuB9dR+brYR2X6U/OqmQPVhpv0akyj0VsQcG5Vs+lZtdLj8jNkq3X8UT+qewruA4BbMkdR+uubh+0wlA80/agMUBM3eBbyXvWq/vFYIue6hic3b0zHxuw7z24tdiApT6oIoUpZ35WOid11heZRN6LWPcba2xJ1XF8W3qHEIM/oddS+3S/L8pFjKaDXbhVj/phy/OBp1Ufh98re62xIEfn2oNxkqMFVRWypEvFPszmHx0Twoy+zg6paAmidUFbCxo/AhZEykjoTGbwWfKeUeCzZnjA95QEhwk+ID2spSNjwZ9TKdA88zn5JJ1V2jOq05G8YemDrDlCYjDhKM/qjWDFc86YfUcIg4W8F3ufWOEKHB7EVb6xMoRoDyChODQkUyILWWlmO5/VMIRhbnSe9tRIhgSjrtKDr4Q4FBEi9Cdn83+911zQ6hMHZG9yjT+2MQ//0cFpSiYni7j1gaxjANZ07VxxhXjIHA7ViI96zNALNkomqBa25k6xFQA/Jn4lOlDu4gUkE4aWoJQelSgqZ3Do/SqJna6jK4hbCN57+D3zMGqEw6TVryi87uH8JuXOvS1/COKNwA1Cj5u+wvh5S24cVwzkTSsqnh4UAdybf/ALGhu3PbWFl0mwRgX2KdftM7JC0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
