travis:
  secure:
    BINSTAR_TOKEN: cQUrxFLWVX4V4AniaaLF27vz9N3A0nbemPonXFfROXCP4r9DuKEovZ06+0eMh4YOefxUhL9J0Ekw3lPDJBSk5vGPZzZg1ahSaQmEqRzQ6YpT4FTaAW5RrAVb6fGS2kG0Sb8W/u0GAafNd3aJDlNpdNiiJ44p5CEY9c99cKUegGGc44hOP5LIkrFlMm1NNZTKSL++lpBdzhMi2I76JLhAyl6M/On9iEV0DEpjZZYLQ2jHlVeFrDNEEi4NFzMqTCwLy8p9wLYYGirIaV8ocR+I/UePzfgmpNN4b6N/IVKNHNv70A7LcxDMb1hZ/BYpg/tT317n+aafpfMC0xRGW9B9VqICoR9mp83+kt8XsGjlxw7WIkNonZmHKKVXbMBAO8eUbXZnVxOgEcKXdoRPXKA/3UiHfmDtDKwM9tlRJTbcVEkYFefwptSGC185xaOHdiZcnSe5TQ45IyWjlqxFrVXPCCKArSqHhFDEkgwXaGuL56vOLTQW2jFe//XMrKqv6c2gXQlUGUvviBzLSC8QDw9jhhUC9CGuax8MB09pZoDEkjAxIaxzvyeQVPqWzAyf1aYx2XmE5rDFkXnzdJgFHlH8mog3tAp/ei5n7wxldCWNtrOK6y0oSJVFZmMP4kT35aSa0qyikrpoG0ExY8B/OcJzDOoLP8PnDwtDoS2QYd558SA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
